name: Github Pipeline
on:
  push:
    branches:
      - main

jobs:

  Deploy-Backend-To-Sandbox:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install nodejs
          node -v
          sudo apt install npm
          npm -v
          npm install -g aws-cdk

          cdk --version
          ls -l

          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
          aws -h

      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile ipo-warning
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}  --profile ipo-warning
          aws configure set default.region eu-west-1  --profile ipo-warning

      - name: Deploy
        run: |
          cd cloud
          yarn
          cdk bootstrap --profile ipo-warning
          yarn diff
          yarn fast-deploy

