name: Github Pipeline
on:
  push:
    branches:
      - main

jobs:

  Deploy-To-Sandbox:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: sandbox
      DATA_API_URL: https://arnnvraxch.execute-api.eu-west-1.amazonaws.com/sandbox/stocks
    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install nodejs
          node -v
          sudo apt install npm
          npm -v
          npm install -g aws-cdk
          cdk --version
          sudo apt install jq
          jq --version

          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
          aws -h



      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile ipo-warning
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}  --profile ipo-warning
          aws configure set default.region eu-west-1  --profile ipo-warning

      - name: Deploy-Backend
        run: |
          cd backend
          yarn
          cdk bootstrap --profile ipo-warning
          yarn diff
          yarn fast-deploy --all
          API_URL=$(aws cloudformation describe-stacks | jq '.Stacks | .[] | .Outputs | reduce .[] as $i ({}; .[$i.OutputKey] = $i.OutputValue) | .sandboxSubscribeURL' | grep -v 'null')
          export API_URL=$API_URL

      - name: Deploy-Frontend
        run: |
          cd frontend
          yarn
          yarn build
          aws s3 sync ./out s3://ipo-warning-s3-bucket-sandbox/



  Deploy-To-Production:
    needs: Deploy-To-Sandbox
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production
      DATA_API_URL: https://arnnvraxch.execute-api.eu-west-1.amazonaws.com/sandbox/stocks
    steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install nodejs
          node -v
          sudo apt install npm
          npm -v
          npm install -g aws-cdk
          cdk --version
          sudo apt install jq
          jq --version

          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
          aws -h

      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile ipo-warning
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}  --profile ipo-warning
          aws configure set default.region eu-west-1  --profile ipo-warning

      - name: Deploy-Backend
        run: |
          cd backend
          yarn
          cdk bootstrap --profile ipo-warning
          yarn diff
          yarn fast-deploy --all
          API_URL=$(aws cloudformation describe-stacks | jq '.Stacks | .[] | .Outputs | reduce .[] as $i ({}; .[$i.OutputKey] = $i.OutputValue) | .sandboxSubscribeURL' | grep -v 'null')
          export API_URL=$API_URL

      - name: Deploy-Frontend
        run: |
          cd frontend
          yarn
          yarn build
          aws s3 sync ./out s3://ipo-warning-s3-bucket-production/

